# Generated by Django 4.2.1 on 2023-06-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtos', models.JSONField()),
                ('preco_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('parcelas', models.PositiveIntegerField()),
                ('id_caixa', models.PositiveIntegerField()),
            ],
        ),
    ]
