# Generated by Django 4.2.1 on 2023-06-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='venda',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
